/**
 * Copyright (c) 2000-2010 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.alacrity.openingdesign.messageportlet.model.service.base;

import com.alacrity.openingdesign.messageportlet.model.model.SKQuestion;
import com.alacrity.openingdesign.messageportlet.model.service.SKQuestionLocalService;
import com.alacrity.openingdesign.messageportlet.model.service.persistence.SKQuestionPersistence;

import com.liferay.counter.service.CounterLocalService;

import com.liferay.portal.kernel.annotation.BeanReference;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdate;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdateFactoryUtil;
import com.liferay.portal.kernel.dao.orm.DynamicQuery;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.util.OrderByComparator;
import com.liferay.portal.service.ResourceLocalService;
import com.liferay.portal.service.ResourceService;
import com.liferay.portal.service.UserLocalService;
import com.liferay.portal.service.UserService;
import com.liferay.portal.service.persistence.ResourcePersistence;
import com.liferay.portal.service.persistence.UserPersistence;

import java.util.List;

import javax.sql.DataSource;

/**
 * The base implementation of the s k question local service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link com.alacrity.openingdesign.messageportlet.model.service.impl.SKQuestionLocalServiceImpl}.
 * </p>
 *
 * <p>
 * Never modify or reference this class directly. Always use {@link com.alacrity.openingdesign.messageportlet.model.service.SKQuestionLocalServiceUtil} to access the s k question local service.
 * </p>
 *
 * @author Henricor
 * @see com.alacrity.openingdesign.messageportlet.model.service.impl.SKQuestionLocalServiceImpl
 * @see com.alacrity.openingdesign.messageportlet.model.service.SKQuestionLocalServiceUtil
 * @generated
 */
public abstract class SKQuestionLocalServiceBaseImpl
	implements SKQuestionLocalService {
	/**
	 * Adds the s k question to the database. Also notifies the appropriate model listeners.
	 *
	 * @param skQuestion the s k question to add
	 * @return the s k question that was added
	 * @throws SystemException if a system exception occurred
	 */
	public SKQuestion addSKQuestion(SKQuestion skQuestion)
		throws SystemException {
		skQuestion.setNew(true);

		return skQuestionPersistence.update(skQuestion, false);
	}

	/**
	 * Creates a new s k question with the primary key. Does not add the s k question to the database.
	 *
	 * @param Question_ID the primary key for the new s k question
	 * @return the new s k question
	 */
	public SKQuestion createSKQuestion(long Question_ID) {
		return skQuestionPersistence.create(Question_ID);
	}

	/**
	 * Deletes the s k question with the primary key from the database. Also notifies the appropriate model listeners.
	 *
	 * @param Question_ID the primary key of the s k question to delete
	 * @throws PortalException if a s k question with the primary key could not be found
	 * @throws SystemException if a system exception occurred
	 */
	public void deleteSKQuestion(long Question_ID)
		throws PortalException, SystemException {
		skQuestionPersistence.remove(Question_ID);
	}

	/**
	 * Deletes the s k question from the database. Also notifies the appropriate model listeners.
	 *
	 * @param skQuestion the s k question to delete
	 * @throws SystemException if a system exception occurred
	 */
	public void deleteSKQuestion(SKQuestion skQuestion)
		throws SystemException {
		skQuestionPersistence.remove(skQuestion);
	}

	/**
	 * Performs a dynamic query on the database and returns the matching rows.
	 *
	 * @param dynamicQuery the dynamic query to search with
	 * @return the matching rows
	 * @throws SystemException if a system exception occurred
	 */
	@SuppressWarnings("rawtypes")
	public List dynamicQuery(DynamicQuery dynamicQuery)
		throws SystemException {
		return skQuestionPersistence.findWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Performs a dynamic query on the database and returns a range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS} will return the full result set.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query to search with
	 * @param start the lower bound of the range of model instances to return
	 * @param end the upper bound of the range of model instances to return (not inclusive)
	 * @return the range of matching rows
	 * @throws SystemException if a system exception occurred
	 */
	@SuppressWarnings("rawtypes")
	public List dynamicQuery(DynamicQuery dynamicQuery, int start, int end)
		throws SystemException {
		return skQuestionPersistence.findWithDynamicQuery(dynamicQuery, start,
			end);
	}

	/**
	 * Performs a dynamic query on the database and returns an ordered range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS} will return the full result set.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query to search with
	 * @param start the lower bound of the range of model instances to return
	 * @param end the upper bound of the range of model instances to return (not inclusive)
	 * @param orderByComparator the comparator to order the results by
	 * @return the ordered range of matching rows
	 * @throws SystemException if a system exception occurred
	 */
	@SuppressWarnings("rawtypes")
	public List dynamicQuery(DynamicQuery dynamicQuery, int start, int end,
		OrderByComparator orderByComparator) throws SystemException {
		return skQuestionPersistence.findWithDynamicQuery(dynamicQuery, start,
			end, orderByComparator);
	}

	/**
	 * Counts the number of rows that match the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query to search with
	 * @return the number of rows that match the dynamic query
	 * @throws SystemException if a system exception occurred
	 */
	public long dynamicQueryCount(DynamicQuery dynamicQuery)
		throws SystemException {
		return skQuestionPersistence.countWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Gets the s k question with the primary key.
	 *
	 * @param Question_ID the primary key of the s k question to get
	 * @return the s k question
	 * @throws PortalException if a s k question with the primary key could not be found
	 * @throws SystemException if a system exception occurred
	 */
	public SKQuestion getSKQuestion(long Question_ID)
		throws PortalException, SystemException {
		return skQuestionPersistence.findByPrimaryKey(Question_ID);
	}

	/**
	 * Gets a range of all the s k questions.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS} will return the full result set.
	 * </p>
	 *
	 * @param start the lower bound of the range of s k questions to return
	 * @param end the upper bound of the range of s k questions to return (not inclusive)
	 * @return the range of s k questions
	 * @throws SystemException if a system exception occurred
	 */
	public List<SKQuestion> getSKQuestions(int start, int end)
		throws SystemException {
		return skQuestionPersistence.findAll(start, end);
	}

	/**
	 * Gets the number of s k questions.
	 *
	 * @return the number of s k questions
	 * @throws SystemException if a system exception occurred
	 */
	public int getSKQuestionsCount() throws SystemException {
		return skQuestionPersistence.countAll();
	}

	/**
	 * Updates the s k question in the database. Also notifies the appropriate model listeners.
	 *
	 * @param skQuestion the s k question to update
	 * @return the s k question that was updated
	 * @throws SystemException if a system exception occurred
	 */
	public SKQuestion updateSKQuestion(SKQuestion skQuestion)
		throws SystemException {
		skQuestion.setNew(false);

		return skQuestionPersistence.update(skQuestion, true);
	}

	/**
	 * Updates the s k question in the database. Also notifies the appropriate model listeners.
	 *
	 * @param skQuestion the s k question to update
	 * @param merge whether to merge the s k question with the current session. See {@link com.liferay.portal.service.persistence.BatchSession#update(com.liferay.portal.kernel.dao.orm.Session, com.liferay.portal.model.BaseModel, boolean)} for an explanation.
	 * @return the s k question that was updated
	 * @throws SystemException if a system exception occurred
	 */
	public SKQuestion updateSKQuestion(SKQuestion skQuestion, boolean merge)
		throws SystemException {
		skQuestion.setNew(false);

		return skQuestionPersistence.update(skQuestion, merge);
	}

	/**
	 * Gets the s k question local service.
	 *
	 * @return the s k question local service
	 */
	public SKQuestionLocalService getSKQuestionLocalService() {
		return skQuestionLocalService;
	}

	/**
	 * Sets the s k question local service.
	 *
	 * @param skQuestionLocalService the s k question local service
	 */
	public void setSKQuestionLocalService(
		SKQuestionLocalService skQuestionLocalService) {
		this.skQuestionLocalService = skQuestionLocalService;
	}

	/**
	 * Gets the s k question persistence.
	 *
	 * @return the s k question persistence
	 */
	public SKQuestionPersistence getSKQuestionPersistence() {
		return skQuestionPersistence;
	}

	/**
	 * Sets the s k question persistence.
	 *
	 * @param skQuestionPersistence the s k question persistence
	 */
	public void setSKQuestionPersistence(
		SKQuestionPersistence skQuestionPersistence) {
		this.skQuestionPersistence = skQuestionPersistence;
	}

	/**
	 * Gets the counter local service.
	 *
	 * @return the counter local service
	 */
	public CounterLocalService getCounterLocalService() {
		return counterLocalService;
	}

	/**
	 * Sets the counter local service.
	 *
	 * @param counterLocalService the counter local service
	 */
	public void setCounterLocalService(CounterLocalService counterLocalService) {
		this.counterLocalService = counterLocalService;
	}

	/**
	 * Gets the resource local service.
	 *
	 * @return the resource local service
	 */
	public ResourceLocalService getResourceLocalService() {
		return resourceLocalService;
	}

	/**
	 * Sets the resource local service.
	 *
	 * @param resourceLocalService the resource local service
	 */
	public void setResourceLocalService(
		ResourceLocalService resourceLocalService) {
		this.resourceLocalService = resourceLocalService;
	}

	/**
	 * Gets the resource remote service.
	 *
	 * @return the resource remote service
	 */
	public ResourceService getResourceService() {
		return resourceService;
	}

	/**
	 * Sets the resource remote service.
	 *
	 * @param resourceService the resource remote service
	 */
	public void setResourceService(ResourceService resourceService) {
		this.resourceService = resourceService;
	}

	/**
	 * Gets the resource persistence.
	 *
	 * @return the resource persistence
	 */
	public ResourcePersistence getResourcePersistence() {
		return resourcePersistence;
	}

	/**
	 * Sets the resource persistence.
	 *
	 * @param resourcePersistence the resource persistence
	 */
	public void setResourcePersistence(ResourcePersistence resourcePersistence) {
		this.resourcePersistence = resourcePersistence;
	}

	/**
	 * Gets the user local service.
	 *
	 * @return the user local service
	 */
	public UserLocalService getUserLocalService() {
		return userLocalService;
	}

	/**
	 * Sets the user local service.
	 *
	 * @param userLocalService the user local service
	 */
	public void setUserLocalService(UserLocalService userLocalService) {
		this.userLocalService = userLocalService;
	}

	/**
	 * Gets the user remote service.
	 *
	 * @return the user remote service
	 */
	public UserService getUserService() {
		return userService;
	}

	/**
	 * Sets the user remote service.
	 *
	 * @param userService the user remote service
	 */
	public void setUserService(UserService userService) {
		this.userService = userService;
	}

	/**
	 * Gets the user persistence.
	 *
	 * @return the user persistence
	 */
	public UserPersistence getUserPersistence() {
		return userPersistence;
	}

	/**
	 * Sets the user persistence.
	 *
	 * @param userPersistence the user persistence
	 */
	public void setUserPersistence(UserPersistence userPersistence) {
		this.userPersistence = userPersistence;
	}

	/**
	 * Performs an SQL query.
	 *
	 * @param sql the sql query to perform
	 */
	protected void runSQL(String sql) throws SystemException {
		try {
			DataSource dataSource = skQuestionPersistence.getDataSource();

			SqlUpdate sqlUpdate = SqlUpdateFactoryUtil.getSqlUpdate(dataSource,
					sql, new int[0]);

			sqlUpdate.update();
		}
		catch (Exception e) {
			throw new SystemException(e);
		}
	}

	@BeanReference(type = SKQuestionLocalService.class)
	protected SKQuestionLocalService skQuestionLocalService;
	@BeanReference(type = SKQuestionPersistence.class)
	protected SKQuestionPersistence skQuestionPersistence;
	@BeanReference(type = CounterLocalService.class)
	protected CounterLocalService counterLocalService;
	@BeanReference(type = ResourceLocalService.class)
	protected ResourceLocalService resourceLocalService;
	@BeanReference(type = ResourceService.class)
	protected ResourceService resourceService;
	@BeanReference(type = ResourcePersistence.class)
	protected ResourcePersistence resourcePersistence;
	@BeanReference(type = UserLocalService.class)
	protected UserLocalService userLocalService;
	@BeanReference(type = UserService.class)
	protected UserService userService;
	@BeanReference(type = UserPersistence.class)
	protected UserPersistence userPersistence;
}