/**
 * Copyright (c) 2000-2010 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.openingdesign.qna.service.base;

import com.liferay.counter.service.CounterLocalService;

import com.liferay.portal.kernel.annotation.BeanReference;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdate;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdateFactoryUtil;
import com.liferay.portal.kernel.dao.orm.DynamicQuery;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.util.OrderByComparator;
import com.liferay.portal.service.ResourceLocalService;
import com.liferay.portal.service.ResourceService;
import com.liferay.portal.service.UserLocalService;
import com.liferay.portal.service.UserService;
import com.liferay.portal.service.persistence.ResourcePersistence;
import com.liferay.portal.service.persistence.UserPersistence;

import com.liferay.portlet.asset.service.AssetEntryLocalService;
import com.liferay.portlet.asset.service.AssetEntryService;
import com.liferay.portlet.asset.service.persistence.AssetEntryPersistence;
import com.liferay.portlet.social.service.SocialActivityLocalService;
import com.liferay.portlet.social.service.persistence.SocialActivityPersistence;

import com.openingdesign.qna.model.QueryAndResponse;
import com.openingdesign.qna.service.QueryAndResponseLocalService;
import com.openingdesign.qna.service.persistence.QueryAndResponsePersistence;

import java.util.List;

import javax.sql.DataSource;

/**
 * The base implementation of the query and response local service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link com.openingdesign.qna.service.impl.QueryAndResponseLocalServiceImpl}.
 * </p>
 *
 * <p>
 * Never modify or reference this class directly. Always use {@link com.openingdesign.qna.service.QueryAndResponseLocalServiceUtil} to access the query and response local service.
 * </p>
 *
 * @author Alacrity Pty (Ltd)
 * @see com.openingdesign.qna.service.impl.QueryAndResponseLocalServiceImpl
 * @see com.openingdesign.qna.service.QueryAndResponseLocalServiceUtil
 * @generated
 */
public abstract class QueryAndResponseLocalServiceBaseImpl
	implements QueryAndResponseLocalService {
	/**
	 * Adds the query and response to the database. Also notifies the appropriate model listeners.
	 *
	 * @param queryAndResponse the query and response to add
	 * @return the query and response that was added
	 * @throws SystemException if a system exception occurred
	 */
	public QueryAndResponse addQueryAndResponse(
		QueryAndResponse queryAndResponse) throws SystemException {
		queryAndResponse.setNew(true);

		return queryAndResponsePersistence.update(queryAndResponse, false);
	}

	/**
	 * Creates a new query and response with the primary key. Does not add the query and response to the database.
	 *
	 * @param queryId the primary key for the new query and response
	 * @return the new query and response
	 */
	public QueryAndResponse createQueryAndResponse(long queryId) {
		return queryAndResponsePersistence.create(queryId);
	}

	/**
	 * Deletes the query and response with the primary key from the database. Also notifies the appropriate model listeners.
	 *
	 * @param queryId the primary key of the query and response to delete
	 * @throws PortalException if a query and response with the primary key could not be found
	 * @throws SystemException if a system exception occurred
	 */
	public void deleteQueryAndResponse(long queryId)
		throws PortalException, SystemException {
		queryAndResponsePersistence.remove(queryId);
	}

	/**
	 * Deletes the query and response from the database. Also notifies the appropriate model listeners.
	 *
	 * @param queryAndResponse the query and response to delete
	 * @throws SystemException if a system exception occurred
	 */
	public void deleteQueryAndResponse(QueryAndResponse queryAndResponse)
		throws SystemException {
		queryAndResponsePersistence.remove(queryAndResponse);
	}

	/**
	 * Performs a dynamic query on the database and returns the matching rows.
	 *
	 * @param dynamicQuery the dynamic query to search with
	 * @return the matching rows
	 * @throws SystemException if a system exception occurred
	 */
	@SuppressWarnings("rawtypes")
	public List dynamicQuery(DynamicQuery dynamicQuery)
		throws SystemException {
		return queryAndResponsePersistence.findWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Performs a dynamic query on the database and returns a range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS} will return the full result set.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query to search with
	 * @param start the lower bound of the range of model instances to return
	 * @param end the upper bound of the range of model instances to return (not inclusive)
	 * @return the range of matching rows
	 * @throws SystemException if a system exception occurred
	 */
	@SuppressWarnings("rawtypes")
	public List dynamicQuery(DynamicQuery dynamicQuery, int start, int end)
		throws SystemException {
		return queryAndResponsePersistence.findWithDynamicQuery(dynamicQuery,
			start, end);
	}

	/**
	 * Performs a dynamic query on the database and returns an ordered range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS} will return the full result set.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query to search with
	 * @param start the lower bound of the range of model instances to return
	 * @param end the upper bound of the range of model instances to return (not inclusive)
	 * @param orderByComparator the comparator to order the results by
	 * @return the ordered range of matching rows
	 * @throws SystemException if a system exception occurred
	 */
	@SuppressWarnings("rawtypes")
	public List dynamicQuery(DynamicQuery dynamicQuery, int start, int end,
		OrderByComparator orderByComparator) throws SystemException {
		return queryAndResponsePersistence.findWithDynamicQuery(dynamicQuery,
			start, end, orderByComparator);
	}

	/**
	 * Counts the number of rows that match the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query to search with
	 * @return the number of rows that match the dynamic query
	 * @throws SystemException if a system exception occurred
	 */
	public long dynamicQueryCount(DynamicQuery dynamicQuery)
		throws SystemException {
		return queryAndResponsePersistence.countWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Gets the query and response with the primary key.
	 *
	 * @param queryId the primary key of the query and response to get
	 * @return the query and response
	 * @throws PortalException if a query and response with the primary key could not be found
	 * @throws SystemException if a system exception occurred
	 */
	public QueryAndResponse getQueryAndResponse(long queryId)
		throws PortalException, SystemException {
		return queryAndResponsePersistence.findByPrimaryKey(queryId);
	}

	/**
	 * Gets the query and response with the UUID and group id.
	 *
	 * @param uuid the UUID of query and response to get
	 * @param groupId the group id of the query and response to get
	 * @return the query and response
	 * @throws PortalException if a query and response with the UUID and group id could not be found
	 * @throws SystemException if a system exception occurred
	 */
	public QueryAndResponse getQueryAndResponseByUuidAndGroupId(String uuid,
		long groupId) throws PortalException, SystemException {
		return queryAndResponsePersistence.findByUUID_G(uuid, groupId);
	}

	/**
	 * Gets a range of all the query and responses.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS} will return the full result set.
	 * </p>
	 *
	 * @param start the lower bound of the range of query and responses to return
	 * @param end the upper bound of the range of query and responses to return (not inclusive)
	 * @return the range of query and responses
	 * @throws SystemException if a system exception occurred
	 */
	public List<QueryAndResponse> getQueryAndResponses(int start, int end)
		throws SystemException {
		return queryAndResponsePersistence.findAll(start, end);
	}

	/**
	 * Gets the number of query and responses.
	 *
	 * @return the number of query and responses
	 * @throws SystemException if a system exception occurred
	 */
	public int getQueryAndResponsesCount() throws SystemException {
		return queryAndResponsePersistence.countAll();
	}

	/**
	 * Updates the query and response in the database. Also notifies the appropriate model listeners.
	 *
	 * @param queryAndResponse the query and response to update
	 * @return the query and response that was updated
	 * @throws SystemException if a system exception occurred
	 */
	public QueryAndResponse updateQueryAndResponse(
		QueryAndResponse queryAndResponse) throws SystemException {
		queryAndResponse.setNew(false);

		return queryAndResponsePersistence.update(queryAndResponse, true);
	}

	/**
	 * Updates the query and response in the database. Also notifies the appropriate model listeners.
	 *
	 * @param queryAndResponse the query and response to update
	 * @param merge whether to merge the query and response with the current session. See {@link com.liferay.portal.service.persistence.BatchSession#update(com.liferay.portal.kernel.dao.orm.Session, com.liferay.portal.model.BaseModel, boolean)} for an explanation.
	 * @return the query and response that was updated
	 * @throws SystemException if a system exception occurred
	 */
	public QueryAndResponse updateQueryAndResponse(
		QueryAndResponse queryAndResponse, boolean merge)
		throws SystemException {
		queryAndResponse.setNew(false);

		return queryAndResponsePersistence.update(queryAndResponse, merge);
	}

	/**
	 * Gets the query and response local service.
	 *
	 * @return the query and response local service
	 */
	public QueryAndResponseLocalService getQueryAndResponseLocalService() {
		return queryAndResponseLocalService;
	}

	/**
	 * Sets the query and response local service.
	 *
	 * @param queryAndResponseLocalService the query and response local service
	 */
	public void setQueryAndResponseLocalService(
		QueryAndResponseLocalService queryAndResponseLocalService) {
		this.queryAndResponseLocalService = queryAndResponseLocalService;
	}

	/**
	 * Gets the query and response persistence.
	 *
	 * @return the query and response persistence
	 */
	public QueryAndResponsePersistence getQueryAndResponsePersistence() {
		return queryAndResponsePersistence;
	}

	/**
	 * Sets the query and response persistence.
	 *
	 * @param queryAndResponsePersistence the query and response persistence
	 */
	public void setQueryAndResponsePersistence(
		QueryAndResponsePersistence queryAndResponsePersistence) {
		this.queryAndResponsePersistence = queryAndResponsePersistence;
	}

	/**
	 * Gets the counter local service.
	 *
	 * @return the counter local service
	 */
	public CounterLocalService getCounterLocalService() {
		return counterLocalService;
	}

	/**
	 * Sets the counter local service.
	 *
	 * @param counterLocalService the counter local service
	 */
	public void setCounterLocalService(CounterLocalService counterLocalService) {
		this.counterLocalService = counterLocalService;
	}

	/**
	 * Gets the resource local service.
	 *
	 * @return the resource local service
	 */
	public ResourceLocalService getResourceLocalService() {
		return resourceLocalService;
	}

	/**
	 * Sets the resource local service.
	 *
	 * @param resourceLocalService the resource local service
	 */
	public void setResourceLocalService(
		ResourceLocalService resourceLocalService) {
		this.resourceLocalService = resourceLocalService;
	}

	/**
	 * Gets the resource remote service.
	 *
	 * @return the resource remote service
	 */
	public ResourceService getResourceService() {
		return resourceService;
	}

	/**
	 * Sets the resource remote service.
	 *
	 * @param resourceService the resource remote service
	 */
	public void setResourceService(ResourceService resourceService) {
		this.resourceService = resourceService;
	}

	/**
	 * Gets the resource persistence.
	 *
	 * @return the resource persistence
	 */
	public ResourcePersistence getResourcePersistence() {
		return resourcePersistence;
	}

	/**
	 * Sets the resource persistence.
	 *
	 * @param resourcePersistence the resource persistence
	 */
	public void setResourcePersistence(ResourcePersistence resourcePersistence) {
		this.resourcePersistence = resourcePersistence;
	}

	/**
	 * Gets the user local service.
	 *
	 * @return the user local service
	 */
	public UserLocalService getUserLocalService() {
		return userLocalService;
	}

	/**
	 * Sets the user local service.
	 *
	 * @param userLocalService the user local service
	 */
	public void setUserLocalService(UserLocalService userLocalService) {
		this.userLocalService = userLocalService;
	}

	/**
	 * Gets the user remote service.
	 *
	 * @return the user remote service
	 */
	public UserService getUserService() {
		return userService;
	}

	/**
	 * Sets the user remote service.
	 *
	 * @param userService the user remote service
	 */
	public void setUserService(UserService userService) {
		this.userService = userService;
	}

	/**
	 * Gets the user persistence.
	 *
	 * @return the user persistence
	 */
	public UserPersistence getUserPersistence() {
		return userPersistence;
	}

	/**
	 * Sets the user persistence.
	 *
	 * @param userPersistence the user persistence
	 */
	public void setUserPersistence(UserPersistence userPersistence) {
		this.userPersistence = userPersistence;
	}

	/**
	 * Gets the asset entry local service.
	 *
	 * @return the asset entry local service
	 */
	public AssetEntryLocalService getAssetEntryLocalService() {
		return assetEntryLocalService;
	}

	/**
	 * Sets the asset entry local service.
	 *
	 * @param assetEntryLocalService the asset entry local service
	 */
	public void setAssetEntryLocalService(
		AssetEntryLocalService assetEntryLocalService) {
		this.assetEntryLocalService = assetEntryLocalService;
	}

	/**
	 * Gets the asset entry remote service.
	 *
	 * @return the asset entry remote service
	 */
	public AssetEntryService getAssetEntryService() {
		return assetEntryService;
	}

	/**
	 * Sets the asset entry remote service.
	 *
	 * @param assetEntryService the asset entry remote service
	 */
	public void setAssetEntryService(AssetEntryService assetEntryService) {
		this.assetEntryService = assetEntryService;
	}

	/**
	 * Gets the asset entry persistence.
	 *
	 * @return the asset entry persistence
	 */
	public AssetEntryPersistence getAssetEntryPersistence() {
		return assetEntryPersistence;
	}

	/**
	 * Sets the asset entry persistence.
	 *
	 * @param assetEntryPersistence the asset entry persistence
	 */
	public void setAssetEntryPersistence(
		AssetEntryPersistence assetEntryPersistence) {
		this.assetEntryPersistence = assetEntryPersistence;
	}

	/**
	 * Gets the social activity local service.
	 *
	 * @return the social activity local service
	 */
	public SocialActivityLocalService getSocialActivityLocalService() {
		return socialActivityLocalService;
	}

	/**
	 * Sets the social activity local service.
	 *
	 * @param socialActivityLocalService the social activity local service
	 */
	public void setSocialActivityLocalService(
		SocialActivityLocalService socialActivityLocalService) {
		this.socialActivityLocalService = socialActivityLocalService;
	}

	/**
	 * Gets the social activity persistence.
	 *
	 * @return the social activity persistence
	 */
	public SocialActivityPersistence getSocialActivityPersistence() {
		return socialActivityPersistence;
	}

	/**
	 * Sets the social activity persistence.
	 *
	 * @param socialActivityPersistence the social activity persistence
	 */
	public void setSocialActivityPersistence(
		SocialActivityPersistence socialActivityPersistence) {
		this.socialActivityPersistence = socialActivityPersistence;
	}

	/**
	 * Performs an SQL query.
	 *
	 * @param sql the sql query to perform
	 */
	protected void runSQL(String sql) throws SystemException {
		try {
			DataSource dataSource = queryAndResponsePersistence.getDataSource();

			SqlUpdate sqlUpdate = SqlUpdateFactoryUtil.getSqlUpdate(dataSource,
					sql, new int[0]);

			sqlUpdate.update();
		}
		catch (Exception e) {
			throw new SystemException(e);
		}
	}

	@BeanReference(type = QueryAndResponseLocalService.class)
	protected QueryAndResponseLocalService queryAndResponseLocalService;
	@BeanReference(type = QueryAndResponsePersistence.class)
	protected QueryAndResponsePersistence queryAndResponsePersistence;
	@BeanReference(type = CounterLocalService.class)
	protected CounterLocalService counterLocalService;
	@BeanReference(type = ResourceLocalService.class)
	protected ResourceLocalService resourceLocalService;
	@BeanReference(type = ResourceService.class)
	protected ResourceService resourceService;
	@BeanReference(type = ResourcePersistence.class)
	protected ResourcePersistence resourcePersistence;
	@BeanReference(type = UserLocalService.class)
	protected UserLocalService userLocalService;
	@BeanReference(type = UserService.class)
	protected UserService userService;
	@BeanReference(type = UserPersistence.class)
	protected UserPersistence userPersistence;
	@BeanReference(type = AssetEntryLocalService.class)
	protected AssetEntryLocalService assetEntryLocalService;
	@BeanReference(type = AssetEntryService.class)
	protected AssetEntryService assetEntryService;
	@BeanReference(type = AssetEntryPersistence.class)
	protected AssetEntryPersistence assetEntryPersistence;
	@BeanReference(type = SocialActivityLocalService.class)
	protected SocialActivityLocalService socialActivityLocalService;
	@BeanReference(type = SocialActivityPersistence.class)
	protected SocialActivityPersistence socialActivityPersistence;
}